# AWSTemplateFormatVersion: "2010-09-09"
# Description: IAM ROLE template
Resources:
  CompassCollectorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "CompassCollectorLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "CompassCollectorLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource:
                  - "Fn::Join":
                    - ":"
                    -
                      - "arn:aws:kinesis"
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - "stream/EventCollectorKinesisStream*"
      Tags:
        -
          Key: "AppName"
          Value: "event-collector"

  DoorkeeperCollectorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "DoorkeeperCollectorLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "DoorkeeperCollectorLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource:
                  - "Fn::Join":
                    - ":"
                    -
                      - "arn:aws:kinesis"
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - "stream/EventCollectorKinesisStream*"
      Tags:
        -
          Key: "AppName"
          Value: "event-collector"

  EventPusherLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "EventPusherLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole"
      Policies:
        - PolicyName: "EventPusherLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:*
                Resource:
                  - "Fn::Join":
                    - ":"
                    -
                      - "arn:aws:kinesis"
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - "stream/EventCollectorKinesisStream"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - "Fn::Join":
                    - ":"
                    -
                      - "arn:aws:secretsmanager"
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - "secret"
                      - "event-collector-secret*"
              - Effect: Allow
                Action:
                  - rds-data:BatchExecuteStatement
                  - rds-data:BeginTransaction
                  - rds-data:CommitTransaction
                  - rds-data:ExecuteStatement
                  - rds-data:RollbackTransaction
                Resource:
                  - "Fn::Join":
                    - ":"
                    -
                      - "arn:aws:rds"
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - "cluster"
                      - "event-collector*"
      Tags:
        -
          Key: "AppName"
          Value: "event-collector"
